### ISSUE TITLE
Alleviating pain of installing Python

### ISSUE THREAD

**Issue by maneesha** [PhillyPythonWorkshop/PhillyPythonWorkshop.github.io#15]
From @FlipperPA

> 
> I'll definitely pitch in. I've actually been thinking about a project...
> 
> Every time I've been to PyCon or DjangoCon (or Wharton) training there's been this pain point: getting people onto the same version of Python on their laptops. I've got an idea to alleviate this.
> 
> I've built a dev system here at work which will stand up a server with Python, virtualenv, virtualenvwrapper, etc for a certain amount of training users. Would this be something we'd be interesting in? It basically means all students would need is a laptop with a terminal (a Mac, or a Windows machine with PuTTY), rather than having to install Python, etc.
> 
> Regards,
> 
> Tim

**Comment by maneesha** [comment]
@FlipperPA
I agree that it's hard to get everyone's Python installation up and working, esp. across operating systems and depending on how their laptops are set up.

However, I do think it's important for them to have a working installation of Python on their own laptops when they leave so they are working in their own environment, they can continue to work on whatever they've learned, and they have a sense of ownership of what they are doing.  

For a  beginner level workshop, differences between 2.x and 3.x can trip people up.  At this point, we do need to have everyone on 3.x, and consider 2.x to be on its way to deprecation.   However, as long as everyone is on some 3.x version, we shouldn't have any problems at the beginner level.  Once they get into more intermediate/advanced stuff, they are going to have to learn how to manage dealing with different versions, so we want to prepare people for that as well.

**Comment by FlipperPA** [comment]
Hehehehe, I've felt 2.x has been deprecated since 2014. :) It's on its way to not being supported! (Sorry if I say that with some glee, maintaining for both has gotten really, really old, heh.)

You're absolutely right about having Python with them to go. It's a pain point that'll have to be encountered at some point. My idea would be more useful for instances like Django development where we can include a PostgreSQL database for each user, pre-reqs, and so on.
